package nl.itc.RIMapper;

import java.util.MissingResourceException;
import java.util.ResourceBundle;

/**
 * Utility class for reading Strings from a messages.properties file.<br/>
 * Generated by MyEclipse StringExternalizer.
 * 
 * @author Barend K&ouml;bben - <a href="mailto:kobben@itc.nl"
 *         target="_blank">kobben@itc.nl</a>
 * @version 1.0 [December 2006]
 */

// Major changes:
// 1.0 [Dec 2006] - first released version
public class Messages {
	private static final String BUNDLE_NAME = "nl.itc.RIMapper.messages"; //$NON-NLS-1$

	private static final ResourceBundle RESOURCE_BUNDLE = ResourceBundle
			.getBundle(BUNDLE_NAME);

	private Messages() {
	}

	public static String getString(String key) {
		try {
			return RESOURCE_BUNDLE.getString(key);
		} catch (MissingResourceException e) {
			return '!' + key + '!';
		}
	}
}
